### ISSUE TITLE
ValidationError: Invalid options object

### ISSUE THREAD

**Issue by Ascyt** [guillaumeduhan/vue-bootstrap-boilerplate#10]
When I try to run the server, I get an error:

```
ValidationError: Invalid options object. Dev Server has been initialized using an options object that does not match the API schema.
         - options has an unknown property 'overlay'. These properties are valid:
           object { allowedHosts?, bonjour?, client?, compress?, devMiddleware?, headers?, historyApiFallback?, host?, hot?, http2?, https?, ipc?, liveReload?, magicHtml?, onAfterSetupMiddleware?, onBeforeSetupMiddleware?, onListening?, open?, port?, proxy?, server?, setupExitSignals?, setupMiddlewares?, static?, watchFiles?, webSocketServer? }
```

Here is my full output on my Windows 11 PC:

``` batch
>npm run serve

> vue-bootstrap-boilerplate@2.2.0 serve
> vue-cli-service serve

 INFO  Starting development server...
 ERROR  ValidationError: Invalid options object. Dev Server has been initialized using an options object that does not match the API schema.
         - options has an unknown property 'overlay'. These properties are valid:
           object { allowedHosts?, bonjour?, client?, compress?, devMiddleware?, headers?, historyApiFallback?, host?, hot?, http2?, https?, ipc?, liveReload?, magicHtml?, onAfterSetupMiddleware?, onBeforeSetupMiddleware?, onListening?, open?, port?, proxy?, server?, setupExitSignals?, setupMiddlewares?, static?, watchFiles?, webSocketServer? }
ValidationError: Invalid options object. Dev Server has been initialized using an options object that does not match the API schema.
 - options has an unknown property 'overlay'. These properties are valid:
   object { allowedHosts?, bonjour?, client?, compress?, devMiddleware?, headers?, historyApiFallback?, host?, hot?, http2?, https?, ipc?, liveReload?, magicHtml?, onAfterSetupMiddleware?, onBeforeSetupMiddleware?, onListening?, open?, port?, proxy?, server?, setupExitSignals?, setupMiddlewares?, static?, watchFiles?, webSocketServer? }
    at validate (C:\Users\filip\Documents\gpt\gpt-story\node_modules\webpack-dev-server\node_modules\schema-utils\dist\validate.js:158:11)
    at new Server (C:\Users\filip\Documents\gpt\gpt-story\node_modules\webpack-dev-server\lib\Server.js:270:5)
    at serve (C:\Users\filip\Documents\gpt\gpt-story\node_modules\@vue\cli-service\lib\commands\serve.js:194:20)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
```

Also it might be worth noting that I'm using Node.js v14.17.3, since I'm unable to install with a newer version, as seen in this issue: #9

**Comment by Ascyt** [comment]
I did manage to make it work my deleting the troublesome property out of the `vue.config.js` file:  

``` javascript
    overlay: {
      warnings: true,
      errors: true
    }
```

Not sure exactly what the point of this property is. Might be worth taking a look at this, though.

**Comment by guillaumeduhan** [comment]
thanks!
